name: apicultores_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: any
  design_system:
    path: packages/design_system
  flutter_blue_plus: ^1.15.8
  permission_handler: ^11.0.0
  connectivity_plus: ^4.0.2
  network_info_plus: ^4.0.2
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  uuid: ^3.0.7
  http: ^1.1.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: 26.1.41+1
  carousel_slider: ^4.2.1
  share_plus: ^7.2.1
  csv: ^5.1.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.3.3
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/apicultores_icon.png"
  adaptive_icon_background: "#f6d107"
  adaptive_icon_foreground: "assets/icon/apicultores_foreground.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  generate: true