name: apicultores_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: any
  design_system:
    path: packages/design_system
  flutter_blue_plus: ^1.15.8
  permission_handler: ^11.0.0
  connectivity_plus: ^4.0.2
  network_info_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true